server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

  mongodb:
    uri: mongodb+srv://microservicios:1234567890@gateway.acp2lp9.mongodb.net/projects_db?appName=Gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

clients:
  users:
    base-url: http://localhost:8081
  notifications:
    base-url: http://localhost:8083

resilience4j:
  circuitbreaker:
    instances:
      notificationsService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      notificationsService:
        maxAttempts: 3
        waitDuration: 500ms

  timelimiter:
    instances:
      notificationsService:
        timeoutDuration: 2s