server:
  port: 8081 # Cada servicio debe tener su propio puerto

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

  data:
    mongodb:
      uri: mongodb+srv://microservicios:1234567890@gateway.acp2lp9.mongodb.net/users_db?appName=Gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always