server:
  port: 8083

spring:
  application:
    name: notifications-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always