server:
  port: 9000

spring:
  application:
    name: iam-service

  mongodb:
    uri: mongodb+srv://microservicios:1234567890@gateway.acp2lp9.mongodb.net/iam_db?appName=Gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always